<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Minify.Application\Minify.Application.csproj" />
      <ProjectReference Include="..\Minify.Communication\Minify.Communication.csproj" />
      <ProjectReference Include="..\Minify.Infrastructure\Minify.Infrastructure.csproj" />
    </ItemGroup>

</Project>
