services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: >-
        Host=db;Port=5432;Database=minify;Username=minify;Password=minify
      ConnectionStrings__Redis: redis:6379
      Hashids__Salt: G5rS0r#O=4PD')|+gp<fMbsr22#C%qp_?FnuGPgp4uYBOSnM
      Hashids__MinLength: 4
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: minify
      POSTGRES_USER: minify
      POSTGRES_PASSWORD: minify
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minify -d minify"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    
volumes:
  postgres_data:
  redis_data: