// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minify.Infrastructure.DataAccess;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Minify.Infrastructure.Migrations
{
    [DbContext(typeof(MinifyDbContext))]
    [Migration("20260814000604_Analytics-UrlAccessEvents")]
    partial class AnalyticsUrlAccessEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Minify.Domain.Entities.ShortUrlEntity", b =>
                {
                    b.Property<string>("ShortenCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShortenCode");

                    b.ToTable("ShortUrls");
                });

            modelBuilder.Entity("Minify.Domain.Entities.UrlAccessEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Referer")
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrafficSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UtmCampaign")
                        .HasColumnType("text");

                    b.Property<string>("UtmMedium")
                        .HasColumnType("text");

                    b.Property<string>("UtmSource")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShortCode", "AccessedAt");

                    b.HasIndex("ShortCode", "Country");

                    b.HasIndex("ShortCode", "TrafficSource");

                    b.ToTable("UrlAccessEvents");
                });

            modelBuilder.Entity("Minify.Domain.Entities.UrlAccessEventEntity", b =>
                {
                    b.HasOne("Minify.Domain.Entities.ShortUrlEntity", null)
                        .WithMany()
                        .HasForeignKey("ShortCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
